// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1N-gSjptRhHMHLhuceItc0os0rfu7ZDY',
    appId: '1:119040493120:web:932f33432b8f1bc4db01a5',
    messagingSenderId: '119040493120',
    projectId: 'gentle-ministry',
    authDomain: 'gentle-ministry.firebaseapp.com',
    storageBucket: 'gentle-ministry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdCefI0wP3zlB3sBrD8hiXX7bJgNSahs',
    appId: '1:119040493120:android:709d8569b275b103db01a5',
    messagingSenderId: '119040493120',
    projectId: 'gentle-ministry',
    storageBucket: 'gentle-ministry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxVQ8jYw39BeRhqv2oW5smnsqtnMK-Dc',
    appId: '1:119040493120:ios:ec4085ffa8b52f19db01a5',
    messagingSenderId: '119040493120',
    projectId: 'gentle-ministry',
    storageBucket: 'gentle-ministry.firebasestorage.app',
    iosBundleId: 'com.localcode.gentleChurch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWxVQ8jYw39BeRhqv2oW5smnsqtnMK-Dc',
    appId: '1:119040493120:ios:ec4085ffa8b52f19db01a5',
    messagingSenderId: '119040493120',
    projectId: 'gentle-ministry',
    storageBucket: 'gentle-ministry.firebasestorage.app',
    iosBundleId: 'com.localcode.gentleChurch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1N-gSjptRhHMHLhuceItc0os0rfu7ZDY',
    appId: '1:119040493120:web:cf4c3459fa662f56db01a5',
    messagingSenderId: '119040493120',
    projectId: 'gentle-ministry',
    authDomain: 'gentle-ministry.firebaseapp.com',
    storageBucket: 'gentle-ministry.firebasestorage.app',
  );
}
